# Generated by Django 5.0.2 on 2024-04-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
    ]
